language: c
dist: trusty
addons:
  apt:
    packages:
      - automake
      - autotools-dev
      - libyajl-dev
      - libseccomp-dev
script:
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure
  - make -j $(nproc)
  - make syntax-check
  - make distcheck
